settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: aranet-cloud
    name: aranet.cloud
    url: 'https://aranet.cloud/'
    method: GET
    expectStatus: 200
    linkable: true

  - id: aranet-com
    name: aranet.com
    url: 'https://aranet.com'
    method: GET
    expectStatus: 200
    linkable: true

  - id: saftehnika-com
    name: saftehnika.com
    url: 'https://saftehnika.com/'
    method: GET
    expectStatus: 200
    linkable: true

  - id: spectrumcompact-com
    name: spectrumcompact.com
    url: 'https://spectrumcompact.com/'
    method: GET
    expectStatus: 200
    linkable: true
